name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  http: ^1.6.0
  local_auth: ^3.0.0
  flutter_native_contact_picker: ^0.0.11
  sip_ua: ^1.1.0
  permission_handler: ^12.0.1
  flutter_webrtc: ^1.3.0
  connectivity_plus: ^7.0.0

  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: assets/icons/icon-foreground.png
  image_path_ios: assets/icons/icon-ios.png

  adaptive_icon_foreground: assets/icons/icon-foreground.png
  adaptive_icon_background: assets/icons/icon-background.png

  android_generate_round_icon: true


flutter:
  uses-material-design: true
  assets:
    - assets/firebase/firebase_options.json
